### ISSUE TITLE
Would like to talk about this project

### ISSUE THREAD

**Issue by aheber** [Ziemniakoss/tree-sitter-apex#1]
I've spent the last couple months independently building a tree-sitter implementation for Apex, SOQL, and SOSL. I'd be interested in discussing with you and reviewing my progress.

I found this project when I went to NPM to see if the name I wanted was available.

If you're interested I'd like to setup a time to chat and maybe show you what I have. I've tried to cover all the parsing scenarios I could think of as well as highlighting.

I'm also very interested in where you might have been planning to benefit from this and what is down the line.

**Comment by Ziemniakoss** [comment]
Hi! To be honest with you, I currently don't have much time for this project. 
I'm currently mainly focusing on my master's thesis.
In free time (which I have something like 4 hours a week) Im trying to finish 2 of my plugins: 
- [lwc-typings-generator](https://github.com/Ziemniakoss/lwc-typings-generator) (I want to finish support for standard library,
implement file watcher and add some features like support for deeper schema typings) and
-  [sfdx-metadata-splitter](https://github.com/Ziemniakoss/sfdx-metadata-splitter) (I want to finally finish support for permission sets and fix unit tests/add more coverage). 

If you want to help me finish this grammar, please fork this project and submit pull request and I will be happy to look at it and merge it if it works. If you don't want to do that, I think that you can create scoped NPM package (like "@aheber/tree-sitter-apex").

Whatever you do, thanks for contacting me!
Have a great day!

**Comment by aheber** [comment]
I have the vast majority of this done; parsing and highlighting are ready to go with a significant number of tests for each. My next steps will be some of the advanced queries like tagging and such.

Would you be interested in seeing how well it could work backing your `lwc-typings-generator`? maybe I can save you some work?

If you don't expect to make much progress on the project would you be interested in releasing the name, assuming my progress meets your needs? Maybe I'm reading that wrong and your plan is to revisit this in the future.

I don't have a lot of interest in releasing a scoped project but will adopt a less than ideal name if needed. Just probing the waters to try and find a better solution.

I understand if you're not at a place that it makes sense to spend time on these questions. If you tell me you're happy with the status quo then I'll be on my way.

Thanks for the response and best of success with your thesis!

**Comment by Ziemniakoss** [comment]
Thanks! 

I plan to come back to this project after finishing things mentioned in message before (in long run I was thinking about creating prettier for apex that doesn't need java to run (or host HTTP server to parse apex under 100ms) and tree-sitter grammar would be perfect for this).

As I said, you can make fork of this repository, add your changes there and make pull request to this repository and if they work I will happily merge it and publish update to npm and crates io package.

As of lwc-typings-generator, grammar defined here is already in use in it (using compiled [WASM](https://github.com/Ziemniakoss/lwc-typings-generator/blob/master/resources/tree-sitter-apex.wasm)). It might not be perfect but its sufficient for method and field names extraction.

**Comment by aheber** [comment]
Prettier is absolutely on my list too.

Have a great day!

**Comment by Ziemniakoss** [comment]
Thanks u 2!
